config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'searches#new'

  # Searches
  get 'searches/new', constraints: { format: :html }
  get 'searches/show', constraints: { format: :html }

  # Words
  scope format: true, constraints: { format: :json } do
    resources :words, only: %i[show index]
  end

  # Cards
  post 'cards/:id/check', to: 'cards#check', as: 'card_check', constraints: { format: :json }
  resources :cards, only: %i[index create show destroy]

  # Users
  get 'auth/register', to: 'searches#new'
  devise_scope :user do
    post 'auth/login', to: 'users/sessions#create'
  end
  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  # Unmatched
  match '*unmatched', to: 'application#not_found_no_logs', via: :all

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_flash.html.erb
<ul class="p-0">
  <% flash.each do |key, val| %>
    <% type = case key %>
    <% when 'notice' then :info %>
    <% when 'alert' then :danger %>
    <% else key %>
    <% end %>
    <%= tag.div val, class: "alert alert-#{type} mt-4", role: "alert" %>
  <% end %>
</ul>

app/views/shared/_login_first.html.erb
<!-- Modal which contains a partial -->
<div class="modal fade" id="loginfirst_modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle"><%= t("u_r_not_authed") %></h5>
        <button type="button" class="close btn btn-danger" data-dismiss="modal" aria-label="Close" onclick="$('#loginfirst_modal').modal('hide');">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="mb-2">
          <%= t("please_login") %>
        </div>
        <%# This works because of Searches helper %>
        <%= render "devise/shared/login_form" %> 
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal" onclick="$('#loginfirst_modal').modal('hide');"><%= t("close") %></button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_lost_connection.html.erb
<!-- Modal -->
<div class="modal fade" id="problems_modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle"><%= t("problems_occured") %></h5>
        <button type="button" class="close btn btn-danger" data-dismiss="modal" aria-label="Close" onclick="$('#problems_modal').modal('hide');">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= t("lost_connection") %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal" onclick="$('#problems_modal').modal('hide');"><%= t("close") %></button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-light sticky-top navbar-expand-lg" style="background-color: #dee2e6;">
  <div class="container">
    <span class="nav-item"><a class="navbar-brand" href="<%= root_path %>">
      <svg class="icon" version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 452.707 452.707" xmlns:xlink="http://www.w3.org/1999/xlink" enable-background="new 0 0 452.707 452.707">
        <g>
          <path d="m234.873,126.705h-12.348c-5.523,0-10,4.477-10,10v43.498 43.498c0,5.523 4.477,10 10,10h21.749c17.506,0 31.749-14.242 31.749-31.749 0-11.08-5.709-20.847-14.336-26.529 3.12-4.913 4.936-10.731 4.936-16.969-0.001-17.506-14.244-31.749-31.75-31.749zm-2.348,20h2.348c6.479,0 11.749,5.271 11.749,11.749s-5.271,11.749-11.749,11.749h-2.348v-23.498zm11.749,66.996h-11.749v-23.498h2.348 9.401c6.478,0 11.749,5.271 11.749,11.749-0.001,6.479-5.271,11.749-11.749,11.749z"/>
          <path d="m310.048,146.708c6.479,0 11.75,5.271 11.75,11.75 0,5.523 4.477,10 10,10s10-4.477 10-10c0-17.507-14.243-31.75-31.75-31.75s-31.75,14.243-31.75,31.75v43.49c0,17.507 14.243,31.75 31.75,31.75s31.75-14.243 31.75-31.75c0-5.523-4.477-10-10-10s-10,4.477-10,10c0,6.479-5.271,11.75-11.75,11.75s-11.75-5.271-11.75-11.75v-43.49c0-6.479 5.271-11.75 11.75-11.75z"/>
          <path d="m150.541,233.383c0.84,0.217 1.682,0.321 2.511,0.321 4.449,0 8.509-2.991 9.675-7.499l3.258-12.598h19.118l3.258,12.599c1.383,5.347 6.839,8.559 12.186,7.177 5.347-1.383 8.561-6.838 7.178-12.185l-22.499-86.996c-1.142-4.413-5.123-7.496-9.682-7.496s-8.54,3.083-9.682,7.496l-22.499,86.996c-1.383,5.346 1.831,10.802 7.178,12.185zm29.389-39.777h-8.773l4.387-16.962 4.386,16.962z"/>
          <path d="m331.798,242.2h-178.753c-5.523,0-10,4.477-10,10s4.477,10 10,10h178.753c5.523,0 10-4.477 10-10s-4.477-10-10-10z"/>
          <path d="m153.045,116.707h178.753c5.523,0 10-4.477 10-10s-4.477-10-10-10h-178.753c-5.523,0-10,4.477-10,10s4.477,10 10,10z"/>
          <path d="m379.771,0h-262.655c-29.875,0-54.18,24.305-54.18,54.18v344.346c0,29.875 24.305,54.181 54.18,54.181h262.654c5.523,0 10-4.477 10-10v-432.707c0.001-5.523-4.476-10-9.999-10zm-10,344.346h-242.655v-324.346h242.654v324.346zm-262.654-322.85v323.791c-9.048,1.696-17.311,5.639-24.18,11.24v-302.347c0-15.368 10.197-28.398 24.18-32.684zm10,411.211c-18.847,0-34.18-15.333-34.18-34.181 0-18.847 15.333-34.18 34.18-34.18h252.654v10.18h-230.654c-5.523,0-10,4.477-10,10s4.477,10 10,10h230.655v8h-60.655c-5.523,0-10,4.477-10,10s4.477,10 10,10h60.655v10.181h-252.655z"/>
        </g>
      </svg>
    </a></span>
    <% if user_signed_in? %>
      <span class="navbar-nav ms-3">
            <%= link_to t('learn'), get_random_card, class: 'nav-link' %>
      </span>
      <span class="nav-item dropdown ms-auto badge">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          <%= current_user&.email %>
        </a>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
          <li><a class="dropdown-item" href="<%= edit_user_registration_path %>"><%= t("my_profile") %></a></li>
          <li><a class="dropdown-item" href="<%= cards_path %>"><%= t("my_cards") %></a></li>
          <li><hr class="dropdown-divider"></li>
          <li><%= link_to t("sign_out"), destroy_user_session_path, method: :delete, class: 'dropdown-item' %></li>
        </ul>
      </span>

    <% else %>
      <ul class="navbar-nav mr-auto list-group list-group-horizontal">
        <span class="nav-item me-1">
          <a class="nav-link" href="<%= new_user_session_path %>"><%= t("sign_in") %></a>
        </span>
        <span class="nav-item ms-1">
          <a class="nav-link" href="<%= new_user_registration_path %>"><%= t("sign_up") %></a>
        </span>
      </ul>
    <% end %>
  </div>
  
</nav>