config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'searches#new'

  # Searches
  get 'searches/new', constraints: { format: :html }
  get 'searches/show', constraints: { format: :html }

  # Words
  scope format: true, constraints: { format: :json } do
    resources :words, only: %i[show index]
  end

  # Cards
  post 'cards/:id/check', to: 'cards#check', as: 'card_check', constraints: { format: :json }
  resources :cards, only: %i[index create show destroy]

  # Users
  get 'auth/register', to: 'searches#new'
  devise_scope :user do
    post 'auth/login', to: 'users/sessions#create'
  end
  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  # Unmatched
  match '*unmatched', to: 'application#not_found_no_logs', via: :all

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/word.rb
class Word < ApplicationRecord
  validates :phrase, presence: true

  def self.dedupe
    # find all models and group them on keys which should be common
    grouped = all.group_by{ |model| [model.phrase] }
    grouped.values.each do |duplicates|
      duplicates.shift # keep the first word
      # if there are any more left, they are duplicates
      # so delete all of them
      duplicates.each { |el| el.destroy } # duplicates can now be destroyed
    end
  end

  def self.search(search)
    find_by phrase: search if search
  end
end

app/controllers/words_controller.rb
# frozen_string_literal: true

require 'http'

# Words controller class
class WordsController < ApplicationController
  include WordsHelper
  before_action :set_word, only: %i[show edit update destroy]

  # GET /words.json
  def index
    if params[:search]
      @found = find_word word_search_params[:phrase]
      redirect_to @found if @found.is_a? Word

      if @found.is_a?(Hash) && @found.length.zero?
        @error = true
        @message = 'Word not found'
      end
    else
      not_found_no_logs
    end
  end

  # GET /words/1.json
  def show
    @word_api = HTTP.get("#{Rails.application.config_for(:webapi)[:url]}/#{@word.phrase}").to_s
    raise StandardError if @word_api[0] != '['
  rescue StandardError
    @error = true
    @message = 'API GET failed'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_word
    @word = Word.find(params[:id])
  end

  # Only allow a list of trusted parameters for search.
  def word_search_params
    phrase = params[:search][:phrase]
    params[:search][:phrase] = phrase.length <= 1 ? phrase : phrase.downcase
    params.require(:search).permit(:phrase, :part_of_speech)
  end
end

app/helpers/words_helper.rb
module WordsHelper
  def find_word(input)
    return Word.search(input) if Word.search(input)

    result = Word.all.inject({}) do |acc, record|
      acc.merge({ record.phrase => DamerauLevenshtein.distance(record.phrase, input) })
    end.filter { |_key, val| val <= 1 }
    result.length == 1 ? Word.search(result.keys[0]) : result
  end
end

app/views/words/_form.html.erb
<%= form_with(model: word) do |form| %>
  <% if word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(word.errors.count, "error") %> prohibited this word from being saved:</h2>

      <ul>
        <% word.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :phrase %>
    <%= form.text_field :phrase %>
  </div>

  <div class="field">
    <%= form.label :groups %>
    <%= form.text_field :groups %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/words/edit.html.erb
<h1>Editing Word</h1>

<%= render 'form', word: @word %>

<%= link_to 'Show', @word %> |
<%= link_to 'Back', words_path %>

app/views/words/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Words</h1>

<table>
  <thead>
    <tr>
      <th>Phrase</th>
      <th>Groups</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @words.each do |word| %>
      <tr>
        <td><%= word.phrase %></td>
        <td><%= word.groups %></td>
        <td><%= link_to 'Show', word %></td>
        <td><%= link_to 'Edit', edit_word_path(word) %></td>
        <td><%= link_to 'Destroy', word, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Word', new_word_path %>
<%= link_to "Advanced Search", new_search_path %>

app/views/words/new.html.erb
<h1>New Word</h1>

<%= render 'form', word: @word %>

<%= link_to 'Back', words_path %>