config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'searches#new'

  # Searches
  get 'searches/new', constraints: { format: :html }
  get 'searches/show', constraints: { format: :html }

  # Words
  scope format: true, constraints: { format: :json } do
    resources :words, only: %i[show index]
  end

  # Cards
  post 'cards/:id/check', to: 'cards#check', as: 'card_check', constraints: { format: :json }
  resources :cards, only: %i[index create show destroy]

  # Users
  get 'auth/register', to: 'searches#new'
  devise_scope :user do
    post 'auth/login', to: 'users/sessions#create'
  end
  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  # Unmatched
  match '*unmatched', to: 'application#not_found_no_logs', via: :all

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
  validates :word, presence: true
  validates :definition, presence: true
end

app/controllers/cards_controller.rb
# frozen_string_literal: true

# Cards controller. It interacts with users
class CardsController < ApplicationController
  include CardsHelper
  before_action :set_card, only: %i[show destroy check]
  before_action :authenticate_user!

  # GET /cards or /cards.json
  def index
    @cards = Card.where(user_id: current_user).order(created_at: :desc)
  end

  # GET /cards/1 or /cards/1.json
  def show
    @card.definition.chop! if @card.definition[-1] == '.'
  end

  # POST /cards/1/check.json
  def check
    @response = make_response(card_params[:word], @card.word)
    @user_action = params[:button]
  end

  # POST /cards or /cards.json
  def create
    @card = Card.new(card_params)
    @card.user_id = current_user.id
    @card.save
  end

  # DELETE /cards/1 or /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: I18n.t('cards.destroyed') }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_card
    @card = Card.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def card_params
    params.require(:card).permit(:word, :definition)
  end
end

app/helpers/cards_helper.rb
module CardsHelper
  def get_random_card
    Card.where(user_id: current_user)[rand * Card.where(user_id: current_user).count]
  end

  def make_response(input, correct)
    correct.gsub!(/ \(.*\)/, '').downcase!
    input.strip!
    input.downcase!
    return { status: 'correct' } if correct == input

    {
      status: :incorrect,
      DL_distance: DamerauLevenshtein.distance(correct, input),
      answer: correct
    }
  end
end

app/views/cards/_card_script.js.erb
window.addEventListener("turbolinks:load", () => {
  const card_form = document.querySelector('#card_form');
  if (card_form) {
    card_form.addEventListener("ajax:success", (event) => { 
      const [_data, _status, xhr] = event.detail;
      let xhr_obj = JSON.parse(xhr.response);

      show_result(xhr_obj);
    });
    card_form.addEventListener("ajax:error", () => {
      $('#problems_modal').modal('show');
    });

    window.addEventListener("keyup", function(event) {
      // If right or down arrow is clicked, go next.
      if (event.keyCode === 39 || event.keyCode === 40) {
        $('#next_card_btn')[0].click();
      }
    });
  }
});

function show_result(respond) {
  let result = respond.result;
  let user_action = respond.for;
  let card = document.querySelector("#my_card");
  card.querySelector("div.card-footer")?.remove();
  let card_body = document.querySelector("#my_card_body");
  let card_footer = document.createElement("div");
  card_footer.id = "result_footer";
  card.appendChild(card_footer);
  card_footer.classList = "card-footer ";

  let btn_check = document.querySelector("#check_submit");
  let btn_dontrem = document.querySelector("#show_answer_submit");
  let word_input = document.querySelector("#card_word")

  if (user_action === "Check") {
    if (result.status === "correct") {
      card.classList = "card border-success";
      card_body.classList = "card-body text-success";
      card_footer.classList += "text-white bg-success";
      card_footer.innerText = "<%= t("cards.script.correct") %>";
      word_input.disabled = true;
      btn_check.hidden = true;
      btn_dontrem.hidden = true;
    }
    else if (result.DL_distance === 1) {
      card.classList = "card border-warning";
      card_body.classList = "card-body";
      card_footer.classList += "bg-warning";
      card_footer.innerHTML = `<%= t("cards.script.almost_correct") %> <em>${result.answer}</em>`;
    }
    else {
      card.classList = "card border-danger";
      card_body.classList = "card-body text-danger";
      card_footer.classList += "text-white bg-danger";
      card_footer.innerText = "<%= t("cards.script.not_correct") %>";
    }
  }
  else {
    card.classList = "card border-warning";
    card_body.classList = "card-body";
    card_footer.classList += "bg-warning";
    card_footer.innerHTML = `<%= t("cards.script.show_correct_is") %> <em>${result.answer}</em>`;
    btn_check.hidden = true;
    btn_dontrem.hidden = true;
    word_input.disabled = true;
  }
}

app/views/cards/index.html.erb
<h3><%= t(".my_cards") %></h3>

<table class="table table-hover">
  <thead>
    <tr>
      <th><%= t(".word") %></th>
      <th class="hide_me"><%= t(".definition") %></th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @cards.each do |card| %>
      <tr>
        <td><%= link_to card.word, card, class: 'hidden_link word_phrase' %></td>
        <td class="hide_me"><%= card.definition %></td>
        <td class="align-middle"><%= button_to t(".delete"), card, type: :button, class: "btn btn-danger", method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/cards/show.html.erb
<% content_for :script do %>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  <script> <%= render partial: 'card_script', formats: [:js] %> </script>
<% end %>

<div class="card" id="my_card">
  <div class="card-header">
    <%= t(".guess") %>
  </div>
  <div class="card-body" id="my_card_body">
    <h5 class="card-title"><%= t(".question") %></h5>
    <p class="card-text"><%= @card.definition %></p>
  </div>

  <%= form_with model: @card, id: :card_form, local: false, url: card_check_path(@card, :json), method: :post, format: :json do |f| %>
    <div class="m-3">
        <%= f.text_field :word, value: nil, class: 'form-control input_field' %>
    </div>
    <%= button_tag t(".check_answer"), id: 'check_submit', class: 'btn btn-primary m-2', type: 'submit', value: 'Check' %>
    <%= button_tag t(".dont_remember_answer"), id: 'show_answer_submit', class: 'btn btn-warning m-2', type: 'submit', value: "Don't remember" %>
  <% end %>
</div>

<br>
<%= button_to t(".next_card"), get_random_card, type: :button, class: "btn btn-success float-end", id: 'next_card_btn', method: :get %>

<%= render 'shared/lost_connection' %>